
ifeq ($(MET_TOP),)
	obj-$(CONFIG_MTK_MET) := met.o
else
ifeq ($(CONFIG_MTK_MET),)
	obj-m := met.o
endif
endif

met-y := met_main.o buffer.o src_map.o sampler.o \
	 interface.o v7_pmu.o v7_pmu_hw.o \
	 util.o \
	 met_tag.o \
	 trace.o \
	 stat.o

met-$(CONFIG_CPU_FREQ) += power.o

ccflags-y := -DMET_USER_EVENT_SUPPORT

