MTK_CPU = arm_cortexa7

TARGET_ARCH_VARIANT = armv7-a-neon


MTK_ENGINEERMODE_INTERNAL_APP = yes

MTK_FIRST_MD = 1
MTK_FOTA_ENTRY = no
MTK_FLIGHT_MODE_POWER_OFF_MD = yes


MTK_SCOMO_ENTRY = no

MTK_OGM_PLAYBACK_SUPPORT = no

MTK_CHKIMGSIZE_SUPPORT = yes
MTK_MMPROFILE_SUPPORT=yes

MTK_DP_FRAMEWORK = yes
MTK_ION_SUPPORT = no

MTK_ENABLE_MD1 = yes
MTK_ENABLE_MD2 = no


CUSTOM_KERNEL_SSW=ssw_single

MTK_SWIP_VORBIS=yes

MULTI_CH_PLAYBACK_SUPPORT=no

MTK_MERGE_INTERFACE_SUPPORT=yes

MTK_PRODUCT_INFO_SUPPORT=yes

HAVE_MTKLOUDNESS_EFFECT=yes
MTK_VSS_SUPPORT = yes

NATIVE_AUDIO_PREPROCESS_ENABLE=no

DMNR_TUNNING_AT_MODEMSIDE=yes

MTK_NATIVE_FENCE_SUPPORT = yes

MTK_PQ_SUPPORT=yes    
MTK_FM_RX_AUDIO=FM_DIGITAL_INPUT
MTK_BWC_SUPPORT = yes

# common part
MTK_COMBO_SUPPORT=yes
CUSTOM_HAL_COMBO=mt6572_82
CUSTOM_HAL_ANT=mt6582_ant_m1
MTK_COMBO_CHIP=MT6572_CONSYS
MTK_COMBO_CORE_DUMP_SUPPORT=no
MTK_COMBO_QUICK_SLEEP_SUPPORT=no

# Bluetooth chip type
MTK_BT_CHIP=MTK_CONSYS_MT6572

MTK_LCEEFT_SUPPORT = yes 

MTK_WFD_SUPPORT=yes

GEMINI=yes
MTK_GEMINI_3G_SWITCH=yes
MTK_GEMINI_ENHANCEMENT=yes
MTK_SHARE_MODEM_CURRENT=2
MTK_SHARE_MODEM_SUPPORT=2

MTK_WLAN_SUPPORT = yes

# the compiler option for HWUI using OpenGLES2.0
USE_OPENGL_RENDERER=true

MTK_MD_SHUT_DOWN_NT = yes 


MTK_SEC_SECRO_AC_SUPPORT = yes 

MTK_SEC_CHIP_SUPPORT = yes

# Enable Scatter file as YAML format
MTK_YAML_SCATTER_FILE_SUPPORT=yes

MTK_GPS_SUPPORT=yes
MTK_YGPS_APP=yes
MTK_GPS_CHIP=MTK_GPS_MT6572

MTK_UART_USB_SWITCH = yes 

MTK_SIP_SUPPORT = no

MTK_WB_SPEECH_SUPPORT = yes 
MTK_DATAUSAGE_SUPPORT = no 

MTK_SUPPORT_MJPEG = yes 

MTK_SINA_WEIBO_SUPPORT =no

MTK_MEMORY_COMPRESSION_SUPPORT=yes

MTK_USE_RESERVED_EXT_MEM=no

MTK_NAND_PAGE_SIZE=4K

MTK_MEM_PRESERVED_MODE_ENABLE = yes 

