/*
 * Generated by MTK SP Drv_CodeGen Version 03.06.0 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Mon Sep 30 10:49:01 2013
 * Do Not Modify the File.
 */



#ifdef __CUST_NEW__
#include "pmic_drv.h"


void pmu_drv_tool_customization_init(void)
{
}
#endif /* __CUST_NEW__ */




